Load Sloth

In [1]:
import slothpy as slt

Import additional packages

In [2]:
import numpy as np
import matplotlib.pyplot as plt

In [31]:
DyCo = slt.compound_from_orca(".", "Lorenzo_Co", "rot_orca", ".", "rot.out")

In [32]:
DyCo = slt.compound_from_orca(".", "Lorenzo_Co", "no_rot_orca", ".", "no_rot.out")

In [4]:
DyCo = slt.compound_from_molcas(".", "Lorenzo_Co", "no_rot", ".", "no_rot_lorenzo_bas0")

In [3]:
DyCo = slt.compound_from_molcas(".", "Lorenzo_Co", "rot", ".", "rot_lorenzo_bas0_corr")

To obtain energies of spin-orbit states you can run:

In [5]:
DyCo.soc_energies_cm_1("no_rot", 6)

array([0.00000000e+00, 4.75909676e-13, 2.43302869e+02, 2.43302869e+02,
       7.24048610e+02, 7.24048610e+02])

In [6]:
DyCo.soc_energies_cm_1("rot", 6)

array([0.00000000e+00, 9.51819353e-13, 2.43300128e+02, 2.43300128e+02,
       7.24054962e+02, 7.24054962e+02])

In [5]:
g_tensor, axes = DyCo.calculate_g_tensor_and_axes_doublet("rot", [0,1])

In [6]:
g_tensor

array([[0.        , 0.04038119, 0.04124371, 9.60611473],
       [1.        , 3.235436  , 3.25472584, 4.59184894]])

In [7]:
axes

array([[[-1.46441413e-03, -9.99998804e-01, -4.97897718e-04],
        [-9.99998547e-01,  1.46484782e-03, -8.71785683e-04],
        [ 8.72513985e-04,  4.96620339e-04, -9.99999496e-01]],

       [[ 9.99986584e-01,  5.15451356e-03,  5.11678170e-04],
        [-5.15261737e-03,  9.99980099e-01, -3.64044545e-03],
        [-5.30432713e-04,  3.63776013e-03,  9.99993243e-01]]])

In [8]:
g_tensor, axes = DyCo.calculate_g_tensor_and_axes_doublet("no_rot", [0,1])

In [9]:
g_tensor

array([[0.        , 0.04037966, 0.04124218, 9.60613229],
       [1.        , 3.23536241, 3.25465008, 4.59191828]])

In [10]:
axes

array([[[-0.37234899,  0.88008991, -0.29461498],
        [-0.8118157 , -0.15500841,  0.56296329],
        [ 0.44979051,  0.44879188,  0.77218803]],

       [[ 0.87870093, -0.37691472,  0.29295044],
        [-0.15797733, -0.80869081, -0.56662363],
        [ 0.45047512,  0.45161318, -0.77014135]]])

In [13]:
rot_trans = np.array([[-1.46441413e-03, -9.99998804e-01, -4.97897718e-04],
        [-9.99998547e-01,  1.46484782e-03, -8.71785683e-04],
        [ 8.72513985e-04,  4.96620339e-04, -9.99999496e-01]])

rot_trans = rot_trans.T

cfp_rot = DyCo.soc_crystal_field_parameters("rot", 0, 3, 2, rotation = rot_trans)

cfp_rot_cm_1 = np.array(cfp_rot)

for i in range(cfp_rot_cm_1.shape[0]):
    cfp_rot_cm_1 [i,2] = cfp_rot_cm_1 [i,2] * 219474.6
    
cfp_rot_cm_1



array([[ 0.00000000e+00,  0.00000000e+00,  1.21649818e+02],
       [ 2.00000000e+00, -2.00000000e+00,  9.97134823e-03],
       [ 2.00000000e+00, -1.00000000e+00, -1.31703813e-02],
       [ 2.00000000e+00,  0.00000000e+00, -9.93195554e+01],
       [ 2.00000000e+00,  1.00000000e+00, -1.86964554e-01],
       [ 2.00000000e+00,  2.00000000e+00,  1.66955458e+00]])

In [12]:
rot_trans = np.array([[-0.37234899,  0.88008991, -0.29461498],
        [-0.8118157 , -0.15500841,  0.56296329],
        [ 0.44979051,  0.44879188,  0.77218803]])

rot_trans = rot_trans.T

cfp = DyCo.soc_crystal_field_parameters("no_rot", 0, 3, 2, rotation= rot_trans)

cfp_cm_1 = np.array(cfp)

for i in range(cfp_cm_1 .shape[0]):
    cfp_cm_1 [i,2] = cfp_cm_1 [i,2] * 219474.6
    
cfp_cm_1

array([[ 0.00000000e+00,  0.00000000e+00,  1.21651434e+02],
       [ 2.00000000e+00, -2.00000000e+00, -9.97927879e-03],
       [ 2.00000000e+00, -1.00000000e+00,  1.32504672e-02],
       [ 2.00000000e+00,  0.00000000e+00, -9.93208760e+01],
       [ 2.00000000e+00,  1.00000000e+00, -1.86978892e-01],
       [ 2.00000000e+00,  2.00000000e+00,  1.66951504e+00]])

In [17]:
cfp = DyCo.soc_crystal_field_parameters("no_rot", 0, 3, 2)

cfp_cm_1 = np.array(cfp)

for i in range(cfp_cm_1 .shape[0]):
    cfp_cm_1 [i,2] = cfp_cm_1 [i,2] * 219474.6
    
cfp_cm_1

array([[  0.        ,   0.        , 121.65143446],
       [  2.        ,  -2.        ,  -8.33556005],
       [  2.        ,  -1.        , -93.81283247],
       [  2.        ,   0.        , -63.93488953],
       [  2.        ,   1.        , -51.60519097],
       [  2.        ,   2.        ,   4.83014611]])

In [60]:
for i in cfp:
    print(f"{i[0]} {i[1]} {i[2]* 219474.6}")

0 0 140.09167750067513
2 -2 -0.015022349505134178
2 -1 25.119260814974528
2 0 -94.1132191367354
2 1 59.96045646559236
2 2 -0.5034712790262911


In [17]:
for k in cfp_rot:
    print(f"{k[0]} {k[1]} {k[2]* 219474.6}")

0 0 139.99685848977649
2 -2 0.012002881468232581
2 -1 0.5185473915488832
2 0 -114.30381360695529
2 1 -0.13089081363393285
2 2 -0.6574555341124702


In [62]:
ito_soc_matrix_rot = DyCo.matrix_from_ito("kur")

In [10]:
ito_soc_matrix_no_rot = DyCo.matrix_from_ito("no_rot")

In [63]:
energies, eigenvectors = np.linalg.eigh(ito_soc_matrix_rot)
energies * 219474.6

array([ 11.8114666,  11.8114666, 268.3718884, 268.3718884])

In [12]:
energies, eigenvectors = np.linalg.eigh(ito_soc_matrix_no_rot)
energies * 219474.6

array([3.99221912e-07, 3.99221972e-07, 2.80183355e+02, 2.80183355e+02])

In [58]:
a = np.array([[ 5.78371953e-03,  9.99983087e-01, -6.12403982e-04],
        [ 9.99982768e-01, -5.78309945e-03,  1.00951341e-03],
        [ 1.00595475e-03, -6.18232171e-04, -9.99999303e-01]])
a = np.array([[ 0.2843829, -0.82284046, 0.49199588], [-0.41815955, -0.56825696, -0.70867949], [-0.86271024, 0.00419645, 0.50568116]])

np.linalg.det(a)

-1.0000000038630528

In [65]:
a = np.array(   [[22.101241999999999,        0.0000000000000000,        0.0000000000000000],     
  [-10.830011557286578,        19.265921924777000,        0.0000000000000000],     
  [-6.8320621260590041E-007,  -1.1678048477038437E-006,   39.144832999999970]])
b = a/3
b

array([[ 7.36708067e+00,  0.00000000e+00,  0.00000000e+00],
       [-3.61000385e+00,  6.42197397e+00,  0.00000000e+00],
       [-2.27735404e-07, -3.89268283e-07,  1.30482777e+01]])

In [66]:
for i in range(3):
    print(f'{b[i][0]:1.16f} {b[i][1]:1.16f} {b[i][2]:1.16f}')

7.3670806666666664 0.0000000000000000 0.0000000000000000
-3.6100038524288593 6.4219739749256668 0.0000000000000000
-0.0000002277354042 -0.0000003892682826 13.0482776666666567
